/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activitat9m3uf6;

import javax.swing.JOptionPane;

/**
 *
 * @author hardl
 */
public class EscacsGUI extends javax.swing.JFrame {

    /**
     * Creates new form Escacs
     */
    Tablero tablero;
    int filFicha;
    int colFicha;
    int filDestino;
    int colDestino;
    boolean seleccion = true;
    String jugador = "blanco";

    public String getJugador() {
        return jugador;
    }

    public EscacsGUI() {
        Ficha ficha;
        tablero = new Tablero();

        initComponents();
        rellenarTablero(tablero.getFichas());

        // do {
        //   System.out.println("Turno jugador: " + jugador);
        //} while (tablero.partidaEnCurso());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setPreferredSize(new java.awt.Dimension(600, 600));
        table.setRowHeight(60);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int fil = table.getSelectedRow();
        int col = table.getSelectedColumn();
        Ficha[][] tableroActual = tablero.getFichas();

        if (table.getValueAt(fil, col) != null && seleccion) {
            filFicha = fil;
            colFicha = col;
            String color = tableroActual[filFicha][colFicha].getColor();
            if ((color.equals("negra") && jugador.equals("negro")) || (color.equals("blanca") && jugador.equals("blanco"))) {
                seleccion = false;
            } else {
                JOptionPane.showMessageDialog(null, "ESA FICHA NO ES TUYA");
            }

        } else if (filFicha > -1 && colFicha > -1 && !seleccion) {
            filDestino = fil;
            colDestino = col;
            seleccion = true;
            if (tablero.moverFicha(filFicha, colFicha, filDestino, colDestino, jugador)) {

                tableroActual = tablero.getFichas();
                char pieza = tableroActual[filDestino][colDestino].getTipo();
                table.setValueAt(pieza, filDestino, colDestino);
                table.setValueAt(null, filFicha, colFicha);
                cambiarTurno();

            }

        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FICHA");
        }
        tablero.mostrar();
        if (!tablero.partidaEnCurso()) {
            System.exit(1);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscacsGUI().setVisible(true);
            }
        });
    }

    public void rellenarTablero(Ficha[][] tablero) {

        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero[i].length; j++) {
                if (tablero[i][j] != null) {
                    char pieza = tablero[i][j].getTipo();
                    table.setValueAt(pieza, i, j);

                }

            }

        }

    }

    // METODO CAMBIAR DE TURNO
    public void cambiarTurno() {
        if (jugador.equals("blanco")) {
            jugador = "negro";

        } else {
            jugador = "blanco";

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
