/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activitat9m3uf6;

import javax.swing.JOptionPane;

/**
 *
 * @author hardl
 */
public class EscacsGUI extends javax.swing.JFrame {

    /**
     * Creates new form Escacs
     */
    Tablero tablero;
    int filFicha;
    int colFicha;
    int filDestino;
    int colDestino;
    boolean seleccion = true;
    String jugador = "blanco";
    
    public String getJugador() {
        return jugador;
    }
    
    public EscacsGUI() {
        Ficha ficha;
        tablero = new Tablero();
        
        initComponents();
        rellenarTablero(tablero.getFichas());
        
        // do {
        //   System.out.println("Turno jugador: " + jugador);
        //} while (tablero.partidaEnCurso());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setPreferredSize(new java.awt.Dimension(600, 600));
        table.setRowHeight(60);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });

        jButton1.setText("REINICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("TURNO | BLANCAS (MAYÚSCULAS)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int fil = table.getSelectedRow();
        int col = table.getSelectedColumn();
        Ficha[][] tableroActual = tablero.getFichas();
        
        if (table.getValueAt(fil, col) != null && seleccion) {
            filFicha = fil;
            colFicha = col;
            String color = tableroActual[filFicha][colFicha].getColor();
            if ((color.equals("negra") && jugador.equals("negro")) || (color.equals("blanca") && jugador.equals("blanco"))) {
                seleccion = false;
            } else {
                JOptionPane.showMessageDialog(null, "ESA FICHA NO ES TUYA");
            }
            
        } else if (filFicha > -1 && colFicha > -1 && !seleccion) {
            filDestino = fil;
            colDestino = col;
            seleccion = true;
            if (tablero.moverFicha(filFicha, colFicha, filDestino, colDestino, jugador)) {
                
                tableroActual = tablero.getFichas();
                char pieza = tableroActual[filDestino][colDestino].getTipo();
                table.setValueAt(pieza, filDestino, colDestino);
                table.setValueAt(null, filFicha, colFicha);
                cambiarTurno();
                tablero.mostrar();
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FICHA");
        }
        
        if (!tablero.partidaEnCurso()) {
            int opcion = JOptionPane.showConfirmDialog(this,"Quieres jugar otra partida?","Partida Acabada",JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION){
                reiniciarPartida();
            } else {
                System.exit(1);
            }
        
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reiniciarPartida();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void reiniciarPartida(){
        tablero = new Tablero();
        rellenarTablero(tablero.getFichas());
        jugador = "blanco";
        tablero.mostrar();
        jLabel1.setText("TURNO | BLANCAS (MAYÚSCULAS)");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscacsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscacsGUI().setVisible(true);
            }
        });
    }
    
    public void rellenarTablero(Ficha[][] tablero) {
        
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero[i].length; j++) {
                if (tablero[i][j] != null) {
                    char pieza = tablero[i][j].getTipo();
                    table.setValueAt(pieza, i, j);
                    
                } else {
                    table.setValueAt(null, i, j);
                }
                
            }
            
        }
        
    }

    // METODO CAMBIAR DE TURNO
    public void cambiarTurno() {
        if (jugador.equals("blanco")) {
            jugador = "negro";
            jLabel1.setText("TURNO | NEGRAS (MINÚSCULAS)");
            
        } else {
            jugador = "blanco";
            jLabel1.setText("TURNO | BLANCAS (MAYÚSCULAS)");
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
